// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQPoWsoPTKXzfBh26IDEZBNRcudTuN1VI',
    appId: '1:1059269798601:web:89bfa06718f4e15a55bb18',
    messagingSenderId: '1059269798601',
    projectId: 'workout-f782d',
    authDomain: 'workout-f782d.firebaseapp.com',
    storageBucket: 'workout-f782d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8HQIhUYyZwuN1O02mQ3hWFfxZodWXf7g',
    appId: '1:1059269798601:android:35d989e136a148f355bb18',
    messagingSenderId: '1059269798601',
    projectId: 'workout-f782d',
    storageBucket: 'workout-f782d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7QDOk4def-LoZjuUtzc33R6tt4Uk9LVQ',
    appId: '1:1059269798601:ios:99155a5d1494898e55bb18',
    messagingSenderId: '1059269798601',
    projectId: 'workout-f782d',
    storageBucket: 'workout-f782d.appspot.com',
    iosClientId:
        '1059269798601-sklp5lsd37i8jsslmq8nn4o12braqe01.apps.googleusercontent.com',
    iosBundleId: 'com.example.workout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7QDOk4def-LoZjuUtzc33R6tt4Uk9LVQ',
    appId: '1:1059269798601:ios:4c7b4b3959e17a7555bb18',
    messagingSenderId: '1059269798601',
    projectId: 'workout-f782d',
    storageBucket: 'workout-f782d.appspot.com',
    iosClientId:
        '1059269798601-6s46m4ssijd7op90t8s319qu040ad6lg.apps.googleusercontent.com',
    iosBundleId: 'com.example.workout.RunnerTests',
  );
}
